### ISSUE TITLE
error adding a torrent

### ISSUE THREAD

**Issue by porjo** [anacrolix/confluence#3]
I've tried adding a torrent file but get error:
```bash
$ curl --data "@/home/porjo/Downloads/Fedora-SoaS-Live-x86_64-25.torrent" localhost:8080/metainfo?ih=1428ef237d033dc3c22410d0d4e6a565d1500ca4
error decoding body: bencode: syntax error (offset: 28406): unexpected EOF
```
I checked the torrent file and it is good. Could you provide an example for adding a torrent file? Also could add support for magnet links? Thanks

**Comment by anacrolix** [comment]
I believe you need to use --data-binary, or it will be url encoded. To add magnets, you should decode them first, fill in what you can in a metainfo, and send that.

**Comment by anacrolix** [comment]
I'll provide some code showing how to add a magnet in a while.

**Comment by porjo** [comment]
`--data-binary` did the trick, thanks. I'll try and read the curl man page better next time! ;)

I've modified `withTorrentContext()` to support adding a new torrent without needing to specify `ih` parm - see [here](https://github.com/anacrolix/confluence/compare/master...porjo:master). Just to avoid having to extract the info hash ahead of time. Would you be happy to add if I send a PR?

**Comment by anacrolix** [comment]
I like the idea of getting the ih from the metainfo if the info bytes are present (and the ih param is not), and writing back the hash in the response. But it's not a requirement that the info bytes be present in the posted metainfo, it's actually used to update or modify a torrent already loaded or cached in confluence, or to add a torrent when you only have the info hash, or have decoded a magnet.

I think my preference would be to make a helper to get a Torrent handle as occurs in withTorrentContext, and run that with the ih param, or inferred ih directly in the metainfoHandler, then proceed as usual. Finally return the infohash of the info bytes that were posted, if they were, in the response. This probably means that metainfoHandler shouldn't run the withTorrentContext anymore, since it now needs special behaviour. I don't think the middleware should be consuming the request body, hence this change.

**Comment by anacrolix** [comment]
I think this is fixed. Reopen issue if something else comes up.
